version: '2'
services:
  etcd:
    image: gcr.io/google_containers/etcd:$ETCD_VERSION
    net: "host"
    command: ["/usr/local/bin/etcd", "--addr=127.0.0.1:4001", "--bind-addr=0.0.0.0:4001", "--data-dir=/var/etcd/data"]

  master:
    image: gcr.io/google_containers/hyperkube:$K8S_VERSION
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /dev:/dev
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/lib/kubelet/:/var/lib/kubelet:rw
      - /var/run:/var/run:rw
    net: "host"
    pid: "host"
    privileged: true
    entrypoint: ["/hyperkube"]
    command: ["kubelet", "--containerized", "--hostname-override=127.0.0.1", "--address=0.0.0.0", "--api-servers=http://localhost:8080", "--config=/etc/kubernetes/manifests"]

  service-proxy:
    image: gcr.io/google_containers/hyperkube:$K8S_VERSION
    net: "host"
    privileged: true
    entrypoint: ["/hyperkube"]
    command: ["proxy", "--master=http://127.0.0.1:8080", "--v=2"]
